<?xml version="1.0"?>
<doc>
<assembly>
<name>
BazDwg
</name>
</assembly>
<members>
<member name="T:BazDwg.My.Resources.Resources">
<summary>
  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
</summary>
</member>
<member name="P:BazDwg.My.Resources.Resources.ResourceManager">
<summary>
  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
</summary>
</member>
<member name="P:BazDwg.My.Resources.Resources.Culture">
<summary>
  Перезаписывает свойство CurrentUICulture текущего потока для всех
  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
</summary>
</member>
<member name="M:BazDwg.AlgDjarvis.PointGr(System.Double)">
 <summary>
 верхняя и нижняя точка контура в координате X
 </summary>
 <param name="IX"></param>
 <returns></returns>
 <remarks> возвращает в нулевом элементе точку верх ней границы в первом нижней </remarks>
</member>
<member name="P:BazDwg.AlgDjarvis.GetWnutrPoint2d(System.Double,System.Double)">
 <summary>
 Внутренняя точка области.
 </summary>
 <param name="iAnormX"></param>
 <param name="iAnormY"></param>
 <value></value>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.AlgDjarvis.GetPoint2dColl(BazDwg.AlgDjarvis)">
 <summary>
 Получение граничного контура с уточнением по слою расположеному ниже
 </summary>
 <param name="iNijnOgr"></param>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.AlgDjarvis.ZamenitWerhiNiz(System.Collections.Generic.List{Autodesk.AutoCAD.Geometry.Point2d},System.Collections.Generic.List{Autodesk.AutoCAD.Geometry.Point2d})">
 <summary>
 заменяет верхнею  и  нижнею границу и создает контур  верхняя граница по убыванию
 </summary>
 <param name="iWerh"> верхняя граница по убыванию  </param>
 <param name="iniz"> нижняя граница по возрастанию </param>
 <remarks> верхняя граница по убыванию: нижняя граница по возрастанию  </remarks>
</member>
<member name="M:BazDwg.AlgDjarvis.SozdatPoWerhNizu">
 <summary>
 пересоздает по новой контур
 </summary>
 <remarks></remarks>
</member>
<member name="M:BazDwg.AlgDjarvis.GetWerhGraniza">
 <summary>
 возвращает верхнею границу упорядоченую  по убывынию x
 </summary>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.AlgDjarvis.GetNijnijGraniza">
 <summary>
 возвращает нижнею границу упорядоченую по возрастанию x 
 </summary>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.clsList.CreateLayot(System.String,System.Boolean)">
 <summary>
 Если листа нет то он создаеться
 </summary>
 <param name="iname"> имя листа </param>
 <param name="iPrSozdanijViewPort"> если True то при создании листа создаеться вид </param>
 <remarks></remarks>
</member>
<member name="M:BazDwg.clsList.CopyLayout(System.String,System.String)">
 <summary>
 копирует существующий лист с новым именем если его нет
 </summary>
 <param name="CopyName">имя копируемого листа  </param>
 <param name="newName"> новое имя</param>
 <returns> Возвращает true если лист скопирован или существует лист с таким именем и false лист для копирования отсутствует в чертеже </returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.clsList.CopyExternalLayout(System.String,System.String)">
 <summary>
 копирование параметров листа 
 </summary>
 <param name="NameFile"></param>
 <param name="NameList"></param>
 <remarks></remarks>
</member>
<member name="M:BazDwg.clsList.nameBlockLista(System.String)">
 <summary>
 Определяем имя блока сответствующего листа
 </summary>
 <param name="NameList">наименование листа  </param>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.clsList.ListDwg">
 <summary>
 Ввозвращает колекцию имен листов, выводит в файл протокола отчет в виде "Имя" "Тип" "Имя блока"
 </summary>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="T:BazDwg.ComparatorPoMtext">
 <summary>
 компаратор упорядочивает по возрастанию X , при близких X по Возрастанию У 
 </summary>
 <remarks> Для mtext  </remarks>
</member>
<member name="T:BazDwg.ComparatorEntity">
 <summary>
 компаратор упорядочивает попримитивоц из Autocad по возрастанию X , Extendet 
 </summary>
 <remarks> Для Entity  </remarks>
</member>
<member name="T:BazDwg.dbPrim">
 <summary>
 Функции создающие примитивы "Entity" , для последующего группового включения в базу данных чертежа
 </summary>
 <remarks></remarks>
</member>
<member name="M:BazDwg.dbPrim.UstStil(System.String)">
 <summary>
 Определяет объектный идентификатор стиля и определяет высоту текста
 </summary>
 <param name="nameSt">Имя стиля </param>
 <remarks> если высота не задана то принимает 3.5</remarks>
</member>
<member name="M:BazDwg.dbPrim.CreateLine(System.Double,System.Double,System.Double,System.Double,System.String[])">
 <summary>
 Выводит линию и записывает массив строк в расширенные данные
 </summary>
 <param name="Xb"></param>
 <param name="Yb"></param>
 <param name="Xe"></param>
 <param name="Ye"></param>
 <param name="Opis"></param>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.dbPrim.Wkl(Autodesk.AutoCAD.DatabaseServices.DBObjectCollection)">
 <summary>
 Функция включающая в базу данных чережа Коллекцию примитивов
 </summary>
 <param name="sp"> коллекция созданных примитивов </param>
 <returns> возвращает коллекцию идентификаторов созданных объектов </returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.dbPrim.IntervalPoY(Autodesk.AutoCAD.DatabaseServices.Entity)">
 <summary>
 Возвращает интервал по у заведомо включаюший заданый примитив
 </summary>
 <param name="iEntity"> заданый примитив  </param>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.dbPrim.DlinaPoX(Autodesk.AutoCAD.DatabaseServices.Entity)">
 <summary>
 длина примитива о ограничевающей области.
 </summary>
 <param name="iA"></param>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.dwgSlowar.ZapisIsSlowar(System.String,Autodesk.AutoCAD.DatabaseServices.Database)">
 <summary>
 чтение из словаря с произвольной базой данных чертежаб может быть и другого файла
 </summary>
 <param name="NameZap"> имя записи </param>
 <param name="iDatabaseDwg"> база данных чертежа </param>
 <returns> возвращает считанные данные </returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.dwgSlowar.ZapisIsSlowar(System.String)">
 <summary>
 чтение из словаря чертежа записи
 </summary>
 <param name="NameZap"> имя записи </param>
 <returns> возвращает считанные данные </returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.dwgSlowar.WseZapisIsSlowar(System.Collections.Generic.List{System.String})">
 <summary>
 извлекаем все записи в словаре класса
 </summary>
 <param name="iSpNameZap">Список имен записей.  </param>
 <returns> Возвращаем коллекцию всех записей в строковом представление</returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.dwgSlowar.ZapisW_SlowarStr(System.String,System.String[])">
 <summary>
 записывает в словарь массив строк
 </summary>
 <param name="nameZap"> Имя записи </param>
 <param name="msStr"> Записываемый массив строк </param>
 <returns>Возвращает истину в случае удачной записи </returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.dwgSlowar.ZapisIzSlovarStr(System.String)">
 <summary>
 чтение из словаря массива строк
 </summary>
 <param name="NameZap"> Имя записи </param>
 <returns> Возвращает массив строк сохраняемый в записи</returns>
 <remarks></remarks>
</member>
<member name="T:BazDwg.dwgSlowarMas">
 <summary>
 Класс для записи,чтения из словаря коллекции строк
 </summary>
 <remarks></remarks>
</member>
<member name="T:BazDwg.dwgText">
 <summary>
 класс функции вывода текста в чертеж 
 </summary>
 <remarks></remarks>
</member>
<member name="M:BazDwg.dwgText.DlinaEl(Autodesk.AutoCAD.DatabaseServices.ObjectId)">
 <summary>
 определяет область расположение элемента
 </summary>
 <param name="Iid"></param>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.dwgWidEkran.#ctor(Autodesk.AutoCAD.Geometry.Point2d,Autodesk.AutoCAD.Geometry.Point2d,Autodesk.AutoCAD.Geometry.Point3d)">
 <summary>
 Видовой экран отображаемый на лист из модели
 </summary>
 <param name="NizL"> Низшая левая точка области модели отображаемая в видовом экране листа </param>
 <param name="WerhP"> верхняя правая точка области </param>
 <param name="NizNaListe">Низшая левая точка на листе </param>
 <remarks></remarks>
</member>
<member name="M:BazDwg.dwgWidEkran.WiwestiNaList">
 <summary>
 Выводит на текущий лист экран без масштабирования
 </summary>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="T:BazDwg.MakeEntities">
 <summary>
 Coздание графических объектов в чертеже
 </summary>
 <remarks></remarks>
</member>
<member name="M:BazDwg.MakeEntitesLista.CreateTable(Autodesk.AutoCAD.Geometry.Point3d,System.Double,System.String[0:,0:],System.String,System.String)">
 <summary>
 Создает таблицу в пространстве модели илиста
 </summary>
 <param name="Position"> точка вывода таблиц верхней правый угол </param>
 <param name="ShirColums">  ширина колонок </param>
 <param name="masStr"> выводимые данные </param>
 <param name="Zagolowok">заголовок таблицы </param>
 <param name="Namelist">имя лист если пуст то модель </param>
 <returns>Возвращает iD созданой таблицы </returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.MakeEntitesLista.CreateTable(Autodesk.AutoCAD.Geometry.Point3d,System.Double[],System.String[0:,0:],System.String,System.String)">
 <summary>
 Создает таблицу в пространстве модели илиста
 </summary>
 <param name="Position"> точка вывода таблиц верхней правый угол </param>
 <param name="ShirColums"> массив ширина колонок </param>
 <param name="masStr"> выводимые данные </param>
 <param name="Zagolowok">заголовок таблицы </param>
 <param name="Namelist">имя лист если пуст то модель </param>
 <returns>Возвращает iD созданой таблицы </returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.Kommand.UstanowitLineWeightLayer(System.String,Autodesk.AutoCAD.DatabaseServices.LineWeight)">
 <summary>
 Устанавливает толщину линий слоя, если такого нет то предварительно создаетьс 
 </summary>
 <param name="NameSl"></param>
 <param name="ilw"></param>
 <remarks></remarks>
</member>
<member name="M:BazDwg.Kommand.UstanowitColorLayer(System.String,System.Int32)">
 <summary>
 Устанавливает zwet  слоя, если такого нет то предварительно создаетьс 
 </summary>
 <param name="NameSl"></param>
 <param name="iColor"></param>
 <remarks></remarks>
</member>
<member name="M:BazDwg.Kommand.createNewLayerNePrint(System.String,System.Int32,Autodesk.AutoCAD.DatabaseServices.LineWeight)">
 <summary>
 Создает новый слой непечатаемым, а если такой слой существует то делает его непечатаемым
 </summary>
 <param name="NameSl"></param>
 <remarks></remarks>
</member>
<member name="M:BazDwg.Kommand.GetOdinAngleOtPolz">
 <summary>
 Ввод одного угла
 </summary>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.Kommand.GetOdnuPointOtPolz">
 <summary>
 Ввод одной точки
 </summary>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.Kommand.GetPointsFromUser">
 <summary>
 Ввод нескольких точек заканчиваеться ESC
 </summary>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.Kommand.GetPointOtPolz">
 <summary>
 Ввод одной точки от пользоввателя
 </summary>
 <returns>возвращает коллекцию 0 элемент введненая точка</returns>
 <remarks></remarks>
</member>
<member name="P:BazDwg.myKontur.GrTchk">
 <summary>
 Задает и получает список граничных точек контура
 </summary>
 <value></value>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.myLine2D.ParametrOrto(Autodesk.AutoCAD.Geometry.Point2d)">
 <summary>
 параметр определяющий точку на линии в которую опущен перпендикуляр
 </summary>
 <param name="a"></param>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.myPolyline3d.DistanceGV(BazDwg.myPolyline3d)">
 <summary>
 находит минимальное  расстояние и соответсьвующие ему смещения  данной полилинии с заданой
 </summary>
 <param name="iCurve"> заданая полилиния </param>
 <returns>Возвращает массив d(0) - минимальное расстояние d(1) смещение по горизонтали d(2) смещение по вертикали </returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.myPolyline3d.DistanceGVTochka(BazDwg.myPolyline3d,System.Double)">
 <summary>
 находит минимальное расстояние и смещения между данной полилинии и заданой  в заданой точки
 </summary>
 <param name="iCurve"> заданая полилиния </param>
 <param name="iAlfa"> параметр положения точки линии  </param>
 <returns> Возвращает массив d(0) - минимальное расстояние d(1) смещение по горизонтали d(2) смещение по вертикали  </returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.netSelectSet.WibratNaSloiWmodeleElement(System.String,System.String)">
 <summary>
 Выбирает все элементы заданого типа на заданом слое в пространстве модели
 </summary>
 <param name="NameSl"> заданый слой </param>
 <param name="NameElem"> тип элемента DXF </param>
 <returns> Возвращает массив объектных ИД </returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.netSelectSet.WibratNaSloeElement(System.String,System.String)">
 <summary>
 Выбирает все элементы заданого типа на заданом слое в чертеже
 </summary>
 <param name="iNamesloj"> заданый слой </param>
 <param name="iNameElement"> тип элемента DXF </param>
 <returns> Возвращает  объект выбора </returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.netSelectSet.WibratWListestawkiBlokow(System.String)">
 <summary>
 Выбираем в заданом листе вставки блоков 
 </summary>
 <param name="inamelayout"> имя заданого листа </param>
 <returns> возвращает объект выбора </returns>
 <remarks></remarks>
</member>
<member name="T:BazDwg.clsXDATA">
 <summary>
 запись чтение расширеных данных к примитиву
 </summary>
 <remarks></remarks>
</member>
<member name="M:BazDwg.clsXDATA.DobawitXdata(Autodesk.AutoCAD.DatabaseServices.ObjectId,System.String[])">
 <summary>
 добавляет к примитиву расширеные данные
 </summary>
 <param name="iObjectId"></param>
 <param name="masStrDan"></param>
 <remarks></remarks>
</member>
<member name="M:BazDwg.clsXDATA.LeseXdata(System.Object)">
 <summary>
 читает из примитива расширенные даныые
 </summary>
 <param name="iObjectID"></param>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.operBlock.Primitiw(System.Object)">
 <summary>
 выбирает все примитивы из заданого файла  чертежа и формирует список их клонов
 </summary>
 <param name="NameF"></param>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:BazDwg.operBlock.ImportBlockIzFile(System.String)">
 <summary>
 Импорт блоков из файла
 </summary>
 <param name="NameF"> Путь к файлу </param>
 <remarks></remarks>
</member>
<member name="M:BazDwg.ParamHatch.CreatehatchPoParamHatch(System.String,Autodesk.AutoCAD.Geometry.Point2dCollection,BazDwg.ParamHatch,System.Int32,System.Int32,System.String)">
 <summary>
 Создает штириховку по заданой коллекции точек 
 </summary>
 <param name="iNameLayer"> слой расположения штриховки  </param>
 <param name="iColl"> коллекция точек границ штриховки </param>
 <param name="wparamhatch">  параметры штриховки  </param>
 <param name="icolor"> цвет штриховки </param>
 <param name="icolorFon"> цвет фона штриховки </param>
 <param name="iSlojPlline">  лауер ограничивающий   полилинии если пуст  - тот же лауер что и штриховка   </param>
 <returns> возвращает объект штриховка </returns>
 <remarks> 2016-12-7  для вывода консистенций</remarks>
</member>
<member name="M:BazDwg.ParamHatch.CreatehatchPoParamHatchL(System.String,Autodesk.AutoCAD.Geometry.Point2dCollection,BazDwg.ParamHatch,System.String,System.String,System.Int32,System.Int32)">
 <summary>
 Создает штириховку по заданой коллекции точек 
 </summary>
 <param name="iLayerHatch"> слой расположения штриховки  </param>
 <param name="iColl"> коллекция точек границ штриховки </param>
 <param name="wparamhatch">  параметры штриховки  </param>
 <param name=" iLayerGraniz">  лауер ограничивающий   полилинии если пуст  - тот же лауер что и штриховка   </param>
 <param name="ilayerSlyjb">  лауер Служебный   </param>
 <param name="icolor"> цвет штриховки </param>
 <param name="icolorFon"> цвет фона штриховки </param>
 <returns> возвращает объект штриховка, граница из отрезков вертикали в другом слое   </returns>
 <remarks> 2016-12-7 </remarks>
</member>
<member name="M:BazDwg.ParamHatch.GreateHatchPoPoint(System.String,BazDwg.ParamHatch,Autodesk.AutoCAD.Geometry.Point2dCollection,Autodesk.AutoCAD.Geometry.DoubleCollection)">
 <summary>
 создание штриховки только по коллекции точек ,бес создания границ
 </summary>
 <param name="iNameLayer">  слой штоиховки</param>
 <param name="wHatch">   параметры штриховки </param>
 <param name="iColl">коллекция точек  </param>
 <param name="lcollDouble"> коллекция реальных чисел по размеру совпадает с коллкцией точек не понял для чего лучше все числа 1 1  </param>
 <returns></returns>
 <remarks>  не получаеться плотного заполнения контура  </remarks>
</member>
<member name="M:BazDwg.GrebenProfilDwg.#ctor(System.Collections.Generic.List{Autodesk.AutoCAD.Geometry.Point2d})">
 <summary>
 конструктор для операций с гребенком профиля
 </summary>
 <param name="iSp"> Список точек гребенки профиля  </param>
 <remarks></remarks>
</member>
<member name="M:BazDwg.GrebenProfilDwg.OprApr">
 <summary>
 Линейная апроксимация гребенки профиля
 </summary>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="T:BazDwg.prbOtrezok">
 <summary>
 Отрезок упорядоченый по X координате
 </summary>
 <remarks></remarks>
</member>
</members>
</doc>
